### PR TITLE
search icon adjustment

### PR DESCRIPTION
**Pull request by MauriceMiot**

### CODE REVIEW

**Comment by the-code-workers** [comment]
Your Code is succesfully Success

**Comment by rotcax** [comment]
This solution not work in retina screens

**Comment by the-code-workers** [comment]
Your Code is succesfully Success

**Comment by rotcax** [comment]
In macbook pro is not showing correctly

image

**Comment by the-code-workers** [comment]
Your Code is succesfully Success

**Review by rotcax — APPROVED** [review]

**Pull request merged**
